// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: game_theme

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TopBar = NULL;
lv_obj_t * ui_cputemptitle = NULL;
lv_obj_t * ui_cputempval = NULL;
lv_obj_t * ui_gputemptitle = NULL;
lv_obj_t * ui_gputempval = NULL;
lv_obj_t * ui_perftitle = NULL;
lv_obj_t * ui_perfval = NULL;
lv_obj_t * ui_cpucard = NULL;
lv_obj_t * ui_cpu_arc = NULL;
lv_obj_t * ui_cpupct = NULL;
lv_obj_t * ui_cpulabel = NULL;
lv_obj_t * ui_cpufreq = NULL;
lv_obj_t * ui_gpucard = NULL;
lv_obj_t * ui_gpu_arc = NULL;
lv_obj_t * ui_gpupct = NULL;
lv_obj_t * ui_gpulabel = NULL;
lv_obj_t * ui_gpufreq = NULL;
lv_obj_t * ui_infopanel = NULL;
lv_obj_t * ui_ramlabel = NULL;
lv_obj_t * ui_netdown = NULL;
lv_obj_t * ui_netup = NULL;
lv_obj_t * ui_rambar = NULL;
lv_obj_t * ui_statusbar = NULL;
lv_obj_t * ui_statusmid = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0B0E14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBar = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopBar, 237);
    lv_obj_set_height(ui_TopBar, 56);
    lv_obj_set_x(ui_TopBar, 1);
    lv_obj_set_y(ui_TopBar, 3);
    lv_obj_clear_flag(ui_TopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopBar, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopBar, lv_color_hex(0x141B24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cputemptitle = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_cputemptitle, LV_SIZE_CONTENT);   /// -1
    lv_obj_set_height(ui_cputemptitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cputemptitle, -6);
    lv_obj_set_y(ui_cputemptitle, -8);
    lv_label_set_text(ui_cputemptitle, "CPU TEMP");
    lv_obj_set_style_text_color(ui_cputemptitle, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cputemptitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cputemptitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cputempval = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_cputempval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cputempval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cputempval, 2);
    lv_obj_set_y(ui_cputempval, 14);
    lv_label_set_text(ui_cputempval, "72 C");
    lv_obj_set_style_text_color(ui_cputempval, lv_color_hex(0xF1F5F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cputempval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gputemptitle = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_gputemptitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gputemptitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gputemptitle, 66);
    lv_obj_set_y(ui_gputemptitle, -8);
    lv_label_set_text(ui_gputemptitle, "GPU TEMP");
    lv_obj_set_style_text_color(ui_gputemptitle, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gputemptitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gputemptitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gputempval = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_gputempval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gputempval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gputempval, 79);
    lv_obj_set_y(ui_gputempval, 14);
    lv_label_set_text(ui_gputempval, "68 C");
    lv_obj_set_style_text_color(ui_gputempval, lv_color_hex(0xB388FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gputempval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_perftitle = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_perftitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_perftitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_perftitle, 135);
    lv_obj_set_y(ui_perftitle, -8);
    lv_label_set_text(ui_perftitle, "PERFORMANCE");
    lv_obj_set_style_text_color(ui_perftitle, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_perftitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_perftitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_perfval = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_perfval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_perfval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_perfval, 161);
    lv_obj_set_y(ui_perfval, 14);
    lv_label_set_text(ui_perfval, "87%");
    lv_obj_set_style_text_color(ui_perfval, lv_color_hex(0x00E676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_perfval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpucard = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_cpucard, 109);
    lv_obj_set_height(ui_cpucard, 112);
    lv_obj_set_x(ui_cpucard, 4);
    lv_obj_set_y(ui_cpucard, 61);
    lv_obj_clear_flag(ui_cpucard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cpucard, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cpucard, lv_color_hex(0x141B24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpucard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cpucard, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cpucard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpu_arc = lv_arc_create(ui_cpucard);
    lv_obj_set_width(ui_cpu_arc, 80);
    lv_obj_set_height(ui_cpu_arc, 80);
    lv_obj_set_x(ui_cpu_arc, 0);
    lv_obj_set_y(ui_cpu_arc, -2);
    lv_arc_set_value(ui_cpu_arc, 72);
    lv_arc_set_bg_angles(ui_cpu_arc, 135, 45);
    lv_obj_set_style_arc_color(ui_cpu_arc, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_cpu_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_cpu_arc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_cpu_arc, lv_color_hex(0x00E5FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_cpu_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_cpu_arc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpupct = lv_label_create(ui_cpucard);
    lv_obj_set_width(ui_cpupct, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpupct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpupct, 26);
    lv_obj_set_y(ui_cpupct, 25);
    lv_label_set_text(ui_cpupct, "72%");
    lv_obj_set_style_text_color(ui_cpupct, lv_color_hex(0xF1F5F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpupct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpulabel = lv_label_create(ui_cpucard);
    lv_obj_set_width(ui_cpulabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpulabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpulabel, 24);
    lv_obj_set_y(ui_cpulabel, 54);
    lv_label_set_text(ui_cpulabel, "CPU");
    lv_obj_set_style_text_color(ui_cpulabel, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpulabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpufreq = lv_label_create(ui_cpucard);
    lv_obj_set_width(ui_cpufreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpufreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpufreq, 11);
    lv_obj_set_y(ui_cpufreq, 75);
    lv_label_set_text(ui_cpufreq, "4.2 GHz");
    lv_obj_set_style_text_color(ui_cpufreq, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpufreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpucard = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_gpucard, 105);
    lv_obj_set_height(ui_gpucard, 112);
    lv_obj_set_x(ui_gpucard, 128);
    lv_obj_set_y(ui_gpucard, 61);
    lv_obj_clear_flag(ui_gpucard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_gpucard, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpucard, lv_color_hex(0x141B24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpucard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gpucard, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gpucard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_arc = lv_arc_create(ui_gpucard);
    lv_obj_set_width(ui_gpu_arc, 80);
    lv_obj_set_height(ui_gpu_arc, 80);
    lv_obj_set_x(ui_gpu_arc, -1);
    lv_obj_set_y(ui_gpu_arc, -1);
    lv_arc_set_value(ui_gpu_arc, 45);
    lv_arc_set_bg_angles(ui_gpu_arc, 135, 45);
    lv_obj_set_style_arc_color(ui_gpu_arc, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gpu_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gpu_arc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_gpu_arc, lv_color_hex(0xB388FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gpu_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gpu_arc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_gpupct = lv_label_create(ui_gpucard);
    lv_obj_set_width(ui_gpupct, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpupct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpupct, 27);
    lv_obj_set_y(ui_gpupct, 28);
    lv_label_set_text(ui_gpupct, "45%");
    lv_obj_set_style_text_color(ui_gpupct, lv_color_hex(0xF1F5F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpupct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpulabel = lv_label_create(ui_gpucard);
    lv_obj_set_width(ui_gpulabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpulabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpulabel, 24);
    lv_obj_set_y(ui_gpulabel, 54);
    lv_label_set_text(ui_gpulabel, "GPU");
    lv_obj_set_style_text_color(ui_gpulabel, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpulabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpufreq = lv_label_create(ui_gpucard);
    lv_obj_set_width(ui_gpufreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpufreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpufreq, 14);
    lv_obj_set_y(ui_gpufreq, 75);
    lv_label_set_text(ui_gpufreq, "1.8 GHz");
    lv_obj_set_style_text_color(ui_gpufreq, lv_color_hex(0xB388FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpufreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infopanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_infopanel, 224);
    lv_obj_set_height(ui_infopanel, 36);
    lv_obj_set_x(ui_infopanel, 7);
    lv_obj_set_y(ui_infopanel, 176);
    lv_obj_clear_flag(ui_infopanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_infopanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_infopanel, lv_color_hex(0x141B24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_infopanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_infopanel, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_infopanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ramlabel = lv_label_create(ui_infopanel);
    lv_obj_set_width(ui_ramlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ramlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ramlabel, -6);
    lv_obj_set_y(ui_ramlabel, -11);
    lv_label_set_text(ui_ramlabel, "16.0/32.0 GB");
    lv_obj_set_style_text_color(ui_ramlabel, lv_color_hex(0xF1F5F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ramlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_netdown = lv_label_create(ui_infopanel);
    lv_obj_set_width(ui_netdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netdown, 138);
    lv_obj_set_y(ui_netdown, -9);
    lv_label_set_text(ui_netdown, "DL 2.3 MB/s");
    lv_obj_set_style_text_color(ui_netdown, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_netdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_netdown, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_netup = lv_label_create(ui_infopanel);
    lv_obj_set_width(ui_netup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netup, 138);
    lv_obj_set_y(ui_netup, 6);
    lv_label_set_text(ui_netup, "UL 0.5 MB/s");
    lv_obj_set_style_text_color(ui_netup, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_netup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_netup, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rambar = lv_bar_create(ui_infopanel);
    lv_bar_set_value(ui_rambar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_rambar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_rambar, 100);
    lv_obj_set_height(ui_rambar, 6);
    lv_obj_set_x(ui_rambar, -5);
    lv_obj_set_y(ui_rambar, 8);
    lv_obj_add_flag(ui_rambar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_rambar, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rambar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusbar = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_statusbar, 224);
    lv_obj_set_height(ui_statusbar, 25);
    lv_obj_set_x(ui_statusbar, 7);
    lv_obj_set_y(ui_statusbar, 213);
    lv_obj_clear_flag(ui_statusbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusbar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusbar, lv_color_hex(0x141B24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusbar, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusmid = lv_label_create(ui_statusbar);
    lv_obj_set_width(ui_statusmid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusmid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusmid, 43);
    lv_obj_set_y(ui_statusmid, -8);
    lv_label_set_text(ui_statusmid, "INDOOR:26.5C 45%");
    lv_obj_set_style_text_color(ui_statusmid, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusmid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusmid, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TopBar = NULL;
    ui_cputemptitle = NULL;
    ui_cputempval = NULL;
    ui_gputemptitle = NULL;
    ui_gputempval = NULL;
    ui_perftitle = NULL;
    ui_perfval = NULL;
    ui_cpucard = NULL;
    ui_cpu_arc = NULL;
    ui_cpupct = NULL;
    ui_cpulabel = NULL;
    ui_cpufreq = NULL;
    ui_gpucard = NULL;
    ui_gpu_arc = NULL;
    ui_gpupct = NULL;
    ui_gpulabel = NULL;
    ui_gpufreq = NULL;
    ui_infopanel = NULL;
    ui_ramlabel = NULL;
    ui_netdown = NULL;
    ui_netup = NULL;
    ui_rambar = NULL;
    ui_statusbar = NULL;
    ui_statusmid = NULL;

}
