// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: game_theme

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TopBar;
extern lv_obj_t * ui_cputemptitle;
extern lv_obj_t * ui_cputempval;
extern lv_obj_t * ui_gputemptitle;
extern lv_obj_t * ui_gputempval;
extern lv_obj_t * ui_perftitle;
extern lv_obj_t * ui_perfval;
extern lv_obj_t * ui_cpucard;
extern lv_obj_t * ui_cpu_arc;
extern lv_obj_t * ui_cpupct;
extern lv_obj_t * ui_cpulabel;
extern lv_obj_t * ui_cpufreq;
extern lv_obj_t * ui_gpucard;
extern lv_obj_t * ui_gpu_arc;
extern lv_obj_t * ui_gpupct;
extern lv_obj_t * ui_gpulabel;
extern lv_obj_t * ui_gpufreq;
extern lv_obj_t * ui_infopanel;
extern lv_obj_t * ui_ramlabel;
extern lv_obj_t * ui_netdown;
extern lv_obj_t * ui_netup;
extern lv_obj_t * ui_rambar;
extern lv_obj_t * ui_statusbar;
extern lv_obj_t * ui_statusmid;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

